console.log("avanzar");
console.log("eliminar 1");
console.log("avanzar");
console.log("eliminar 1");
console.log("avanzar");
console.log("eliminar 1");
console.log("avanzar");
console.log("eliminar 1");
console.log("girar hacia de izquierda");
console.log("avanzar");
console.log("eliminar 1");
console.log("avanzar");
console.log("eliminar 1");
console.log("avanzar");
console.log("eliminar 1");
console.log("avanzar");
console.log("eliminar 1");
console.log("avanzar");
console.log("eliminar 1");
